
[functions.on-login]
enabled = true
verify_jwt = true
import_map = "./functions/on-login/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/on-login/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/on-login/*.html" ]

[functions.oauth-token]
enabled = true
verify_jwt = false
entrypoint = "./functions/oauth-token/index.ts"

[functions.oauth-authorize]
enabled = true
verify_jwt = false
entrypoint = "./functions/oauth-authorize/index.ts"
