name = "supakey-site"
compatibility_date = "2025-09-05"
workers_dev = true

# Serve the built Vite assets (build to dist before deploying)
[assets]
directory = "dist"
# SPA routing: rewrite unknown paths to index.html
not_found_handling = "single-page-app"

# Optional: when you’re ready to attach a custom domain, replace workers_dev with routes.
 [routes]
 patterns = [
   { pattern = "supakey.app", custom_domain = true },
]
