name = "supakey"
compatibility_date = "2025-09-06"

# routes must be an array of route objects
routes = [
  { pattern = "supakey.app/*", custom_domain = true },
  { pattern = "www.supakey.app/*", custom_domain = true }
]

[assets]
directory = "dist"
not_found_handling = "single-page-application"
